Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -79,25 +79,46 @@ jobs:
           api-level: 29
           arch: arm64-v8a
           profile: Nexus 6
-          script: ./gradlew connectedCheck
+#          script: ./gradlew connectedCheck
           disable-animations: true
           emulator-options: -no-snapshot -no-boot-anim -no-window -no-gpu -accel off -noaudio
 
-      - name: Wait for emulator to boot
+      - name: Create and Start Emulator
         run: |
-          echo "Waiting for the emulator to boot..."
-          timeout=60  # Maximum wait time in seconds
-          while [[ $timeout -gt 0 ]]; do
-            adb devices | grep emulator && break
-            timeout=$((timeout - 5))
-            sleep 5
-          done
-          if [[ $timeout -le 0 ]]; then
-            echo "❌ Emulator failed to boot within the time limit"
-            exit 1
-          else
-            echo "✅ Emulator booted successfully"
-          fi
+            echo "Creating Android Emulator"
+            # Create a new AVD (Android Virtual Device)
+            echo "no" | avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64"
+            # Start the emulator in the background
+            emulator -avd test -no-window -no-snapshot -no-boot-anim -gpu off &
+            # Wait for the emulator to boot
+            timeout=60  # Timeout for the emulator to start (in seconds)
+            while [[ $timeout -gt 0 ]]; do
+              adb devices | grep emulator && break
+              timeout=$((timeout - 5))
+              sleep 5
+            done
+            if [[ $timeout -le 0 ]]; then
+              echo "❌ Emulator failed to boot within the time limit"
+              exit 1
+            else
+              echo "✅ Emulator booted successfully"
+            fi
+
+#      - name: Wait for emulator to boot
+#        run: |
+#          echo "Waiting for the emulator to boot..."
+#          timeout=60  # Maximum wait time in seconds
+#          while [[ $timeout -gt 0 ]]; do
+#            adb devices | grep emulator && break
+#            timeout=$((timeout - 5))
+#            sleep 5
+#          done
+#          if [[ $timeout -le 0 ]]; then
+#            echo "❌ Emulator failed to boot within the time limit"
+#            exit 1
+#          else
+#            echo "✅ Emulator booted successfully"
+#          fi
 
 #      - name: Check connected devices
 #        run: |
@@ -108,6 +129,9 @@ jobs:
 #            else
 #              echo "✅ Emulator connected: $DEVICES"
 #            fi
+
+      - name: Run Espresso tests
+        run: ./gradlew connectedCheck
 
       - name: Upload test report
         uses: actions/upload-artifact@v4
