Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,10 +26,26 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v4
 
-      - name: Create Google Services JSON File
+      - name: Decode google-services.json
         env:
           GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
-        run: $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
+        run: |
+          mkdir -p app
+          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
+
+      - name: Confirm google-services.json exists and is valid JSON
+        run: |
+          if [ ! -s app/google-services.json ]; then
+            echo "google-services.json is missing or empty"
+            exit 1
+          fi
+          jq . app/google-services.json
+      
+      
+      #      - name: Create Google Services JSON File
+#        env:
+#          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
+#        run: $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
 
 
 #        run: |
