Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,13 +33,13 @@ jobs:
           mkdir -p app
           echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
 
-      - name: Confirm google-services.json exists and is valid JSON
-        run: |
-          if [ ! -s app/google-services.json ]; then
-            echo "google-services.json is missing or empty"
-            exit 1
-          fi
-          jq . app/google-services.json
+#      - name: Confirm google-services.json exists and is valid JSON
+#        run: |
+#          if [ ! -s app/google-services.json ]; then
+#            echo "google-services.json is missing or empty"
+#            exit 1
+#          fi
+#          jq . app/google-services.json
       
 
       #      - name: Create Google Services JSON File
