Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -81,17 +81,33 @@ jobs:
           profile: Nexus 6
           script: ./gradlew connectedCheck
           disable-animations: true
-          emulator-options: -no-snapshot -no-boot-anim -no-window
+          emulator-options: -no-snapshot -no-boot-anim -no-window -no-gpu -accel off -noaudio
 
-      - name: Check connected devices
+      - name: Wait for emulator to boot
         run: |
-            DEVICES=$(adb devices | grep emulator | grep device)
-            if [ -z "$DEVICES" ]; then
-              echo "❌ No emulator connected!"
-              exit 1
-            else
-              echo "✅ Emulator connected: $DEVICES"
-            fi
+          echo "Waiting for the emulator to boot..."
+          timeout=60  # Maximum wait time in seconds
+          while [[ $timeout -gt 0 ]]; do
+            adb devices | grep emulator && break
+            timeout=$((timeout - 5))
+            sleep 5
+          done
+          if [[ $timeout -le 0 ]]; then
+            echo "❌ Emulator failed to boot within the time limit"
+            exit 1
+          else
+            echo "✅ Emulator booted successfully"
+          fi
+
+#      - name: Check connected devices
+#        run: |
+#            DEVICES=$(adb devices | grep emulator | grep device)
+#            if [ -z "$DEVICES" ]; then
+#              echo "❌ No emulator connected!"
+#              exit 1
+#            else
+#              echo "✅ Emulator connected: $DEVICES"
+#            fi
 
       - name: Upload test report
         uses: actions/upload-artifact@v4
